### PR TITLE
Join room mutation fix

### PR DESCRIPTION
**Pull request by CurtisUnderwood**
### Description

List of proposed changes:

- Fixed the join room mutation to take timer object and set of cards

### CODE REVIEW

**Review by shewood — COMMENTED** [review]
I tried it out and can connect two users

**Review by MarcoGoC — APPROVED** [review]
this makes sense. but why is the createRoom does not need the same changes?

**Review by P0NDER0SA — APPROVED** [review]
Let's get this stew going

**Review by alexunique0519 — APPROVED** [review]
LGTM

**Pull request merged**
